window.LUMIC_SERVICES=[
  {
    "slug": "pvc-banners-mesh-site-hoardings",
    "category": "soft",
    "title": "PVC Banners, Mesh & Site Hoardings",
    "description": "Large-format banner and mesh printing for construction sites, shopfronts, events and more.",
    "environment": "Outdoor",
    "life": "Medium",
    "coming": false,
    "image": "assets/services/soft-01.webp",
    "options": "Frontlit, blockout and mesh banners; eyelets, hems, pole pockets, framing and installation.",
    "uses": "Construction-site hoardings and fence mesh; shopfront banners; real-estate and auction banners; sporting clubs, schools, events and festivals.",
    "choose": "Choose when you need maximum size and visibility at a low cost per square metre."
  },
  {
    "slug": "backlit-signage-translites",
    "category": "soft",
    "title": "Backlit Signage & Translites",
    "description": "Rich, even colour for illuminated lightboxes, menu boards and displays.",
    "environment": "Indoor + Outdoor",
    "life": "Medium–Long",
    "coming": false,
    "image": "assets/services/soft-02.webp",
    "options": "Backlit banner or film; snap frames and LED lightbox supply.",
    "uses": "Shopping-centre and showroom lightboxes; café and quick-service menu boards; snap-frame displays; medical-centre, pharmacy and pylon signs.",
    "choose": "Choose when your sign needs to glow indoors or stay visible at night."
  },
  {
    "slug": "vinyl-wall-graphics-murals",
    "category": "soft",
    "title": "Vinyl Wall Graphics & Murals",
    "description": "Printed self-adhesive vinyl for offices, retail spaces, schools and feature walls.",
    "environment": "Indoor",
    "life": "Long",
    "coming": false,
    "image": "assets/services/soft-03.webp",
    "options": "Gloss or matte laminate; textured vinyl; removable adhesive.",
    "uses": "Office branding walls; cafés and restaurants; schools; healthcare centres; hotel corridors; retail feature walls.",
    "choose": "Choose when you want a full-wall brand story without paint."
  },
  {
    "slug": "window-graphics-one-way-vision",
    "category": "soft",
    "title": "Window Graphics — One-Way Vision",
    "description": "Perforated window graphics that advertise outside while preserving visibility inside.",
    "environment": "Indoor + Outdoor",
    "life": "Medium",
    "coming": false,
    "image": "assets/services/soft-04.webp",
    "options": "Perforated printed window film, sized to your glazing.",
    "uses": "Retail storefront windows; vehicle windows; promotional glass surfaces.",
    "choose": "Choose for an exterior advertising surface that preserves outward visibility."
  },
  {
    "slug": "frosted-etched-clear-vision-films",
    "category": "soft",
    "title": "Frosted, Etched & Clear Vision Films",
    "description": "Privacy and decorative films for office partitions, reception and glass doors.",
    "environment": "Indoor",
    "life": "Long",
    "coming": false,
    "image": "assets/services/soft-05.webp",
    "options": "Frosted, etched-effect and clear printed window films.",
    "uses": "Office partitions; reception glazing; glass doors; meeting rooms.",
    "choose": "Choose for privacy or decoration while retaining light."
  },
  {
    "slug": "floor-graphics",
    "category": "soft",
    "title": "Floor Graphics",
    "description": "Printed vinyl with anti-slip laminate for exhibitions, retail and wayfinding.",
    "environment": "Indoor",
    "life": "Short–Medium",
    "coming": false,
    "image": "assets/services/soft-06.webp",
    "options": "Custom printed vinyl with suitable anti-slip laminate.",
    "uses": "Retail promotions; event wayfinding; exhibition floors; temporary campaigns.",
    "choose": "Choose when floors can become part of your message."
  },
  {
    "slug": "fleet-vehicle-graphics",
    "category": "soft",
    "title": "Fleet & Vehicle Graphics",
    "description": "Printed vehicle vinyl, partial or full wraps and cut-vinyl lettering.",
    "environment": "Outdoor",
    "life": "Medium–Long",
    "coming": false,
    "image": "assets/services/soft-07.webp",
    "options": "Full wraps; partial wraps; cut-vinyl lettering.",
    "uses": "Cars; vans; trucks; delivery fleets; mobile advertising.",
    "choose": "Choose when you want your vehicle to advertise on the move."
  },
  {
    "slug": "canvas-wallpaper-art-prints",
    "category": "soft",
    "title": "Canvas, Wallpaper & Art Prints",
    "description": "High-resolution prints on canvas, photo media and custom wallpaper.",
    "environment": "Indoor",
    "life": "Long",
    "coming": false,
    "image": "assets/services/soft-08.webp",
    "options": "Canvas prints; photo media; custom wallpaper.",
    "uses": "Residential interiors; office art; hospitality; retail interiors.",
    "choose": "Choose for custom decorative artwork or large interior prints."
  },
  {
    "slug": "exhibition-graphics-pull-up-banners-standees",
    "category": "soft",
    "title": "Exhibition Graphics, Pull-Up Banners & Standees",
    "description": "Portable displays, graphic panels and backdrops for events and exhibitions.",
    "environment": "Indoor",
    "life": "Short–Medium",
    "coming": false,
    "image": "assets/services/soft-09.webp",
    "options": "Pull-up banners; portable displays; backdrops; graphic panels.",
    "uses": "Trade shows; conferences; launches; promotional events.",
    "choose": "Choose for reusable, portable branded displays."
  },
  {
    "slug": "custom-print-cut-stickers",
    "category": "soft",
    "title": "Custom Print & Cut Stickers",
    "description": "Full-colour, contour-cut vinyl stickers in custom shapes and finishes.",
    "environment": "Indoor + Outdoor",
    "life": "Medium",
    "coming": false,
    "image": "assets/services/soft-10.webp",
    "options": "Custom shapes; full-colour contour cutting; a selection of finishes.",
    "uses": "Product labels; promotional stickers; packaging; giveaways.",
    "choose": "Choose for custom-shaped branded stickers."
  },
  {
    "slug": "dtf-textile-printing",
    "category": "soft",
    "title": "DTF Textile Printing",
    "description": "Full-colour heat transfers for garments, merchandise and uniforms.",
    "environment": "Garments",
    "life": "Long",
    "coming": true,
    "image": "assets/services/soft-11.webp",
    "options": "Full-colour heat-transfer designs for compatible garments.",
    "uses": "Custom apparel; uniforms; event merchandise.",
    "choose": "Choose for detailed, full-colour textile decoration."
  },
  {
    "slug": "direct-glass-printing",
    "category": "solid",
    "title": "Direct Glass Printing",
    "description": "Direct UV printing on glass with white underbase and decorative effects.",
    "environment": "Indoor",
    "life": "Long",
    "coming": false,
    "image": "assets/services/solid-01.webp",
    "options": "Direct UV printing with white underbase and decorative effects.",
    "uses": "Glass doors; partitions; splashbacks; decorative interior panels.",
    "choose": "Choose for artwork printed directly onto glass."
  },
  {
    "slug": "acrylic-prints-edge-lit-displays",
    "category": "solid",
    "title": "Acrylic Prints & Edge-Lit Displays",
    "description": "Clear acrylic printing, laser-cut shapes and optional LED edge lighting.",
    "environment": "Indoor",
    "life": "Long",
    "coming": false,
    "image": "assets/services/solid-02.webp",
    "options": "Clear acrylic; laser-cut shapes; optional LED edge lighting.",
    "uses": "Reception signs; awards; illuminated displays; premium decorative pieces.",
    "choose": "Choose for a polished, dimensional acrylic finish."
  },
  {
    "slug": "uv-print-on-timber-mdf-plywood",
    "category": "solid",
    "title": "UV Print on Timber, MDF & Plywood",
    "description": "Direct UV printing on natural timber for signage, furniture and decor.",
    "environment": "Indoor",
    "life": "Long",
    "coming": false,
    "image": "assets/services/solid-03.webp",
    "options": "Grain show-through; CNC-routed shapes; optional clear coat.",
    "uses": "Café menu boards; furniture panels; wall décor; gift boxes; timber signage.",
    "choose": "Choose when natural timber texture should remain visible."
  },
  {
    "slug": "uv-print-on-metal-aluminium-stainless-steel",
    "category": "solid",
    "title": "UV Print on Metal, Aluminium & Stainless Steel",
    "description": "Durable direct print for nameplates, panels, plaques and signs.",
    "environment": "Indoor + Outdoor",
    "life": "Long",
    "coming": false,
    "image": "assets/services/solid-04.webp",
    "options": "Direct UV print on metal substrates and fabricated panels.",
    "uses": "Nameplates; plaques; equipment panels; premium signage.",
    "choose": "Choose for durable printed metal surfaces."
  },
  {
    "slug": "uv-print-on-tiles-ceramics",
    "category": "solid",
    "title": "UV Print on Tiles & Ceramics",
    "description": "Decorative UV printing for tiled feature walls and splashbacks; not for floors.",
    "environment": "Indoor walls",
    "life": "Long",
    "coming": false,
    "image": "assets/services/solid-05.webp",
    "options": "Printed decorative tile and ceramic wall pieces; not for floors.",
    "uses": "Kitchen splashbacks; bathroom feature walls; decorative tiled installations.",
    "choose": "Choose for artwork integrated into tiled walls."
  },
  {
    "slug": "acp-corflute-foamboard-signage",
    "category": "solid",
    "title": "ACP, Corflute & Foamboard Signage",
    "description": "Direct-printed rigid signs for property, safety, directional and retail use.",
    "environment": "Indoor + Outdoor",
    "life": "Medium–Long",
    "coming": false,
    "image": "assets/services/solid-06.webp",
    "options": "Direct print on rigid ACP, Corflute and foamboard panels.",
    "uses": "Real-estate boards; safety and directional signs; retail displays.",
    "choose": "Choose a rigid board according to installation and lifespan needs."
  },
  {
    "slug": "3d-cut-out-letters-signs",
    "category": "solid",
    "title": "3D Cut-Out Letters & Signs",
    "description": "CNC- and laser-cut letters and logos in acrylic, ACP, MDF, foam or metal.",
    "environment": "Indoor + Outdoor",
    "life": "Long",
    "coming": false,
    "image": "assets/services/solid-07.webp",
    "options": "CNC- and laser-cut acrylic, ACP, MDF, foam or metal; optional lighting.",
    "uses": "Reception branding; retail shopfronts; feature walls.",
    "choose": "Choose for dimensional lettering and logos."
  },
  {
    "slug": "point-of-purchase-pop-displays",
    "category": "solid",
    "title": "Point-of-Purchase (POP) Displays",
    "description": "Counter displays, shelf wobblers, hanging signs and product stands.",
    "environment": "Indoor",
    "life": "Short–Medium",
    "coming": false,
    "image": "assets/services/solid-08.webp",
    "options": "Counter displays; shelf wobblers; hanging signs; product stands.",
    "uses": "Retail promotions; cosmetics; food and beverage; product launches.",
    "choose": "Choose to present products at the point of sale."
  },
  {
    "slug": "industrial-labels-overlays-mimic-panels",
    "category": "solid",
    "title": "Industrial Labels, Overlays & Mimic Panels",
    "description": "Durable printed overlays, control-panel fascias and equipment labels.",
    "environment": "Indoor + Outdoor",
    "life": "Long",
    "coming": false,
    "image": "assets/services/solid-09.webp",
    "options": "Control-panel fascias; equipment labels; industrial overlays.",
    "uses": "Machinery; equipment; electrical control panels; safety identification.",
    "choose": "Choose for functional industrial identification."
  },
  {
    "slug": "uv-dtf-transfers",
    "category": "solid",
    "title": "UV DTF Transfers",
    "description": "Raised glossy transfers for curved or uneven product surfaces.",
    "environment": "Products",
    "life": "Long",
    "coming": true,
    "image": "assets/services/solid-10.webp",
    "options": "Raised glossy transfers for hard product surfaces.",
    "uses": "Drinkware; packaging; custom promotional products.",
    "choose": "Choose for a glossy raised decoration without a background border."
  },
  {
    "slug": "uv-dtf-gold-foil-stickers",
    "category": "solid",
    "title": "UV DTF Gold Foil Stickers",
    "description": "Metallic gold foil transfers for premium packaging and gifting.",
    "environment": "Products",
    "life": "Long",
    "coming": true,
    "image": "assets/services/solid-11.webp",
    "options": "Metallic gold foil UV DTF transfers.",
    "uses": "Premium packaging; gifting; branded decorative accents.",
    "choose": "Choose when a metallic finish is central to the design."
  }
];